name: Release SK Platform
on:
  release:
    types: [created]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - run: |
          PAYLOAD=$(echo '${{ toJson(github.event.release) }}' | jq -c .)
          ESCAPED_PAYLOAD=$(jq -Rn --argjson data "$PAYLOAD" '$data')
          curl -X POST \
               -H "Content-Type: application/json" \
               -H "Authorization: Bearer ${{ secrets.DEPLOYMENT_PASSWORD }}" \
               -d '{"type":"release","repository":"SK-Platform", "payload":'"$ESCAPED_PAYLOAD"'}' \
               ${{ secrets.DEPLOYMENT_ENDPOINT }}